[article]
# title = """
# Competition-Induced Handedness Separation and Masturbatory Hand Preference in Right-Handed Men
# """
title = """
The Competition-Induced Handedness Separation Hypothesis: Investigating the Association Between Early Computer Mouse Use and Left-Hand Masturbation Preference Among Right-Handed Men
"""


[[author]]
full_name = "Neruthes"
corresponding = true



